### ISSUE TITLE
Symfony2 is not supported anymore on master

### ISSUE THREAD

**Issue by galphanet** [tweedegolf/prometheus-bundle#4]
When using the `master` branch for Symfony2, the following error arise :

`InvalidArgumentException in YamlFileLoader.php line 148: A service definition must be an array or a string starting with "@" but NULL found for service "TweedeGolf\PrometheusClient\Storage\ApcuAdapter" in services.yml. Check your YAML syntax.`

As there is no breaking changes with Symfony 2, I would recommand to keep backward compatibility for applications that cannot be upgraded.

**Comment by rnijveld** [comment]
If you could make the appropriate changes I can merge them for you, but as we don't use Symfony2 in our organization anymore I don't think we'll have time to support it ourselves.

**Comment by rnijveld** [comment]
I've just pushed some changes that might be suited for making this bundle work with Symfony2.7+, would you be able to test whether this works? If all works well I'll push out a new tagged version. I'm particularly concerned about the routing syntax where Symfony 4 documentation sais that we need two colons for addressing a method in a controller, but Symfony < 3 seems to require just a single colon.

**Comment by galphanet** [comment]
Thanks for your work ! I'll try it and let you know the results.
